spring:
  profiles:
    # 默认激活 dev 环境
    active: dev
    #active: prod
jwt:
  issuer: quanxiaoha # 签发人
  secret: jElxcSUj38+Bnh73T68lNs0DfBSit6U3whQlcGO2XwnI+Bo3g4xsiCIPg8PV/L0fQMis08iupNwhe2PzYLB9Xg== # 秘钥